# Generated by Django 5.2.7 on 2025-11-17 14:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OllamaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='模型名称')),
                ('display_name', models.CharField(max_length=100, verbose_name='显示名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='模型描述')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('is_vision_capable', models.BooleanField(default=False, verbose_name='是否支持视觉分析')),
                ('model_size', models.CharField(blank=True, max_length=50, null=True, verbose_name='模型大小')),
                ('api_endpoint', models.URLField(default='http://localhost:11434', verbose_name='API端点')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'Ollama模型',
                'verbose_name_plural': 'Ollama模型',
            },
        ),
        migrations.CreateModel(
            name='AIAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '等待分析'), ('processing', '分析中'), ('completed', '分析完成'), ('failed', '分析失败')], default='pending', max_length=20, verbose_name='分析状态')),
                ('ai_title', models.CharField(blank=True, max_length=200, null=True, verbose_name='AI生成标题')),
                ('ai_description', models.TextField(blank=True, null=True, verbose_name='AI生成描述')),
                ('ai_prompt', models.TextField(blank=True, null=True, verbose_name='AI生成提示词')),
                ('model_used', models.CharField(blank=True, max_length=100, null=True, verbose_name='使用的AI模型')),
                ('analysis_result', models.JSONField(blank=True, default=dict, verbose_name='分析结果详情')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='错误信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('analyzed_at', models.DateTimeField(blank=True, null=True, verbose_name='分析完成时间')),
                ('media', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_analysis', to='media.media', verbose_name='媒体文件')),
            ],
            options={
                'verbose_name': 'AI分析',
                'verbose_name_plural': 'AI分析',
            },
        ),
        migrations.CreateModel(
            name='BatchAnalysisJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', '等待中'), ('running', '进行中'), ('completed', '已完成'), ('failed', '失败'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='状态')),
                ('total_files', models.IntegerField(default=0, verbose_name='总文件数')),
                ('processed_files', models.IntegerField(default=0, verbose_name='已处理文件数')),
                ('failed_files', models.IntegerField(default=0, verbose_name='失败文件数')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='错误信息')),
                ('progress_percentage', models.FloatField(default=0.0, verbose_name='完成百分比')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('media_files', models.ManyToManyField(related_name='batch_analysis_jobs', to='media.media', verbose_name='媒体文件')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_analysis_jobs', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ollama_ai.ollamamodel', verbose_name='使用的模型')),
            ],
            options={
                'verbose_name': '批量分析任务',
                'verbose_name_plural': '批量分析任务',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SuggestedCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence', models.FloatField(default=0.0, verbose_name='置信度')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('ai_analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggested_categories', to='ollama_ai.aianalysis', verbose_name='AI分析')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_suggestions', to='media.category', verbose_name='分类')),
            ],
            options={
                'verbose_name': '建议分类',
                'verbose_name_plural': '建议分类',
                'unique_together': {('ai_analysis', 'category')},
            },
        ),
        migrations.CreateModel(
            name='SuggestedTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence', models.FloatField(default=0.0, verbose_name='置信度')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('ai_analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggested_tags', to='ollama_ai.aianalysis', verbose_name='AI分析')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_suggestions', to='media.tag', verbose_name='标签')),
            ],
            options={
                'verbose_name': '建议标签',
                'verbose_name_plural': '建议标签',
                'unique_together': {('ai_analysis', 'tag')},
            },
        ),
    ]
