# Generated by Django 5.2.7 on 2025-11-17 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ollama_ai', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ollamamodel',
            name='api_endpoint',
            field=models.URLField(default='http://115.190.140.100:31434', verbose_name='API端点'),
        ),
    ]
