# Generated by Django 5.2.7 on 2026-01-20 14:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media', '0006_remove_media_tags_delete_tag'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='项目名称')),
                ('description', models.TextField(blank=True, verbose_name='项目描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('cover_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cover_for_projects', to='media.media', verbose_name='封面图片')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL, verbose_name='所有者')),
            ],
            options={
                'verbose_name': '项目',
                'verbose_name_plural': '项目',
                'ordering': ['-updated_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0, verbose_name='排序顺序')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_media', to='media.media', verbose_name='媒体文件')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_media', to='projects.project', verbose_name='项目')),
            ],
            options={
                'verbose_name': '项目媒体',
                'verbose_name_plural': '项目媒体',
                'ordering': ['order', '-added_at'],
            },
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['owner'], name='projects_pr_owner_i_dea3a1_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['created_at'], name='projects_pr_created_6b02e3_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['-created_at'], name='projects_pr_created_775fe7_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['updated_at'], name='projects_pr_updated_d6acc2_idx'),
        ),
        migrations.AddIndex(
            model_name='projectmedia',
            index=models.Index(fields=['project'], name='projects_pr_project_e3a804_idx'),
        ),
        migrations.AddIndex(
            model_name='projectmedia',
            index=models.Index(fields=['media'], name='projects_pr_media_i_00a950_idx'),
        ),
        migrations.AddIndex(
            model_name='projectmedia',
            index=models.Index(fields=['order'], name='projects_pr_order_5068db_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='projectmedia',
            unique_together={('project', 'media')},
        ),
    ]
