# Generated by Django 5.2.7 on 2025-12-11 13:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OllamaEndpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='端点名称')),
                ('provider', models.CharField(choices=[('ollama', 'Ollama - 本地部署'), ('zhipu', '智谱AI'), ('openai', 'OpenAI'), ('azure', 'Azure OpenAI'), ('anthropic', 'Anthropic Claude'), ('custom', '自定义API')], default='ollama', max_length=20, verbose_name='供应商类型')),
                ('url', models.URLField(verbose_name='服务端点URL')),
                ('api_key', models.CharField(blank=True, help_text='智谱AI等云服务需要提供API Key', max_length=500, null=True, verbose_name='API Key')),
                ('auth_type', models.CharField(choices=[('none', '无需认证'), ('api_key', 'API Key'), ('bearer_token', 'Bearer Token')], default='none', max_length=20, verbose_name='认证类型')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('is_default', models.BooleanField(default=False, verbose_name='是否为默认端点')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='endpoint_app_endpoints', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
            options={
                'verbose_name': 'AI模型端点',
                'verbose_name_plural': 'AI模型端点',
                'ordering': ['-is_default', '-created_at'],
                'unique_together': {('created_by', 'url')},
            },
        ),
        migrations.CreateModel(
            name='OllamaAIModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ollama中的模型标识，如: llama2:7b', max_length=100, verbose_name='模型名称')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('is_vision_capable', models.BooleanField(choices=[(False, '否 - 仅支持文本'), (True, '是 - 支持图像和文本')], default=False, help_text='模型是否能够处理图像输入', verbose_name='是否支持视觉分析')),
                ('is_default', models.BooleanField(default=False, help_text='用户创建分析任务时的默认选择', verbose_name='是否为默认分析模型')),
                ('model_size', models.CharField(blank=True, help_text='从Ollama API获取的模型大小信息', max_length=50, null=True, verbose_name='模型大小')),
                ('digest', models.CharField(blank=True, help_text='Ollama模型的唯一标识', max_length=100, null=True, verbose_name='模型摘要')),
                ('modified_at', models.DateTimeField(blank=True, help_text='Ollama模型的最后修改时间', null=True, verbose_name='修改时间')),
                ('ollama_info', models.JSONField(blank=True, default=dict, help_text='从Ollama API获取的完整模型信息', verbose_name='Ollama详细信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_models', to='endpoint.ollamaendpoint', verbose_name='所属端点')),
            ],
            options={
                'verbose_name': 'Ollama模型',
                'verbose_name_plural': 'Ollama模型',
                'ordering': ['-is_default', 'name'],
                'indexes': [models.Index(fields=['is_active', 'is_vision_capable'], name='endpoint_ol_is_acti_ea52b0_idx'), models.Index(fields=['name'], name='endpoint_ol_name_a17eeb_idx')],
                'unique_together': {('name', 'endpoint')},
            },
        ),
    ]
