# Generated by Django 5.2.7 on 2025-11-24 08:11

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ollama', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ollamaendpoint',
            unique_together={('created_by', 'url')},
        ),
    ]
