# Generated by Django 5.2.7 on 2025-11-24 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ollama', '0002_alter_ollamaendpoint_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='OllamaAIModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ollama中的模型标识，如: llama2:7b', max_length=100, verbose_name='模型标识名称')),
                ('display_name', models.CharField(help_text='前端显示的友好名称', max_length=100, verbose_name='显示名称')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('is_vision_capable', models.BooleanField(default=False, help_text='模型是否能够处理图像输入', verbose_name='是否支持视觉分析')),
                ('is_default', models.BooleanField(default=False, help_text='用户创建分析任务时的默认选择', verbose_name='是否为默认分析模型')),
                ('analysis_type', models.CharField(choices=[('image', '图像分析'), ('text', '文本分析'), ('multimodal', '多模态分析')], default='multimodal', help_text='模型支持的主要分析类型', max_length=20, verbose_name='分析类型')),
                ('model_size', models.CharField(choices=[('small', '小型模型'), ('medium', '中型模型'), ('large', '大型模型'), ('unknown', '未知大小')], default='unknown', help_text='模型参数规模', max_length=20, verbose_name='模型大小')),
                ('parameter_count', models.CharField(blank=True, help_text='如: 7B, 13B, 70B', max_length=50, null=True, verbose_name='参数数量')),
                ('description', models.TextField(blank=True, help_text='模型特点和使用说明', null=True, verbose_name='模型描述')),
                ('max_input_tokens', models.IntegerField(blank=True, help_text='模型支持的最大输入长度', null=True, verbose_name='最大输入token数')),
                ('response_speed', models.CharField(choices=[('fast', '快速'), ('medium', '中等'), ('slow', '较慢')], default='medium', help_text='模型的生成速度级别', max_length=20, verbose_name='响应速度')),
                ('cost_level', models.CharField(choices=[('low', '低成本'), ('medium', '中等成本'), ('high', '高成本')], default='medium', help_text='模型使用时的资源消耗级别', max_length=20, verbose_name='使用成本')),
                ('recommended_for', models.TextField(blank=True, help_text='推荐的应用场景和使用建议', null=True, verbose_name='推荐用途')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_models', to='ollama.ollamaendpoint', verbose_name='所属端点')),
            ],
            options={
                'verbose_name': 'AI分析模型',
                'verbose_name_plural': 'AI分析模型',
                'ordering': ['-is_default', 'display_name'],
                'indexes': [models.Index(fields=['is_active', 'is_vision_capable'], name='ollama_olla_is_acti_7b8038_idx'), models.Index(fields=['analysis_type'], name='ollama_olla_analysi_235915_idx')],
                'unique_together': {('name', 'endpoint')},
            },
        ),
    ]
