# Generated by Django 5.2.7 on 2025-11-24 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ollama', '0003_ollamaaimodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ollamaaimodel',
            name='analysis_type',
            field=models.CharField(choices=[('image', '图像模型'), ('text', '文本模型')], default='image', help_text='模型类型：图像模型或文本模型', max_length=20, verbose_name='模型类型'),
        ),
    ]
