# Generated by Django 5.2.7 on 2025-11-24 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ollama', '0004_alter_ollamaaimodel_analysis_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ollamaaimodel',
            name='is_vision_capable',
            field=models.BooleanField(choices=[(False, '否 - 仅支持文本'), (True, '是 - 支持图像和文本')], default=False, help_text='模型是否能够处理图像输入', verbose_name='是否支持视觉分析'),
        ),
    ]
