# Generated by Django 5.2.7 on 2025-11-24 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ollama', '0005_alter_ollamaaimodel_is_vision_capable'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ollamaaimodel',
            options={'ordering': ['-is_default', 'name'], 'verbose_name': 'Ollama模型', 'verbose_name_plural': 'Ollama模型'},
        ),
        migrations.RemoveIndex(
            model_name='ollamaaimodel',
            name='ollama_olla_analysi_235915_idx',
        ),
        migrations.RemoveField(
            model_name='ollamaaimodel',
            name='analysis_type',
        ),
        migrations.RemoveField(
            model_name='ollamaaimodel',
            name='cost_level',
        ),
        migrations.RemoveField(
            model_name='ollamaaimodel',
            name='description',
        ),
        migrations.RemoveField(
            model_name='ollamaaimodel',
            name='display_name',
        ),
        migrations.RemoveField(
            model_name='ollamaaimodel',
            name='max_input_tokens',
        ),
        migrations.RemoveField(
            model_name='ollamaaimodel',
            name='parameter_count',
        ),
        migrations.RemoveField(
            model_name='ollamaaimodel',
            name='recommended_for',
        ),
        migrations.RemoveField(
            model_name='ollamaaimodel',
            name='response_speed',
        ),
        migrations.AddField(
            model_name='ollamaaimodel',
            name='digest',
            field=models.CharField(blank=True, help_text='Ollama模型的唯一标识', max_length=100, null=True, verbose_name='模型摘要'),
        ),
        migrations.AddField(
            model_name='ollamaaimodel',
            name='modified_at',
            field=models.DateTimeField(blank=True, help_text='Ollama模型的最后修改时间', null=True, verbose_name='修改时间'),
        ),
        migrations.AddField(
            model_name='ollamaaimodel',
            name='ollama_info',
            field=models.JSONField(blank=True, default=dict, help_text='从Ollama API获取的完整模型信息', verbose_name='Ollama详细信息'),
        ),
        migrations.AlterField(
            model_name='ollamaaimodel',
            name='model_size',
            field=models.CharField(blank=True, help_text='从Ollama API获取的模型大小信息', max_length=50, null=True, verbose_name='模型大小'),
        ),
        migrations.AlterField(
            model_name='ollamaaimodel',
            name='name',
            field=models.CharField(help_text='Ollama中的模型标识，如: llama2:7b', max_length=100, verbose_name='模型名称'),
        ),
        migrations.AddIndex(
            model_name='ollamaaimodel',
            index=models.Index(fields=['name'], name='ollama_olla_name_ae5e78_idx'),
        ),
    ]
