# Generated by Django 5.2.7 on 2025-11-24 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
        ('ollama', '0006_alter_ollamaaimodel_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OllamaImageAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '等待中'), ('processing', '处理中'), ('completed', '已完成'), ('failed', '失败'), ('cancelled', '已取消')], db_index=True, default='pending', max_length=20, verbose_name='任务状态')),
                ('task_id', models.CharField(blank=True, db_index=True, help_text='后台异步任务的唯一标识', max_length=255, null=True, verbose_name='异步任务ID')),
                ('analysis_options', models.JSONField(blank=True, default=dict, help_text='图片分析的配置参数', verbose_name='分析选项')),
                ('prompt', models.TextField(blank=True, null=True, verbose_name='分析提示词')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='错误信息')),
                ('retry_count', models.IntegerField(default=0, verbose_name='重试次数')),
                ('processing_time', models.IntegerField(blank=True, null=True, verbose_name='处理时间(毫秒)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始处理时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('media', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ollama_task', to='media.media', verbose_name='媒体文件')),
                ('model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='ollama.ollamaaimodel', verbose_name='使用的模型')),
            ],
            options={
                'verbose_name': 'Ollama分析任务状态',
                'verbose_name_plural': 'Ollama分析任务状态',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='ollama_olla_status_3322ba_idx'), models.Index(fields=['media', 'status'], name='ollama_olla_media_i_896b38_idx'), models.Index(fields=['task_id'], name='ollama_olla_task_id_3bd3e8_idx')],
            },
        ),
    ]
