# Generated by Django 5.2.7 on 2025-11-24 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
        ('ollama', '0007_ollamaimageanalysis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ollamaimageanalysis',
            name='media',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ollama_analyses', to='media.media', verbose_name='媒体文件'),
        ),
    ]
