# Generated by Django 5.2.7 on 2025-12-10 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ollama', '0009_add_analysis_results_field'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ollamaendpoint',
            options={'ordering': ['-is_default', '-created_at'], 'verbose_name': 'AI模型端点', 'verbose_name_plural': 'AI模型端点'},
        ),
        migrations.AddField(
            model_name='ollamaendpoint',
            name='api_key',
            field=models.CharField(blank=True, help_text='智谱AI等云服务需要提供API Key', max_length=500, null=True, verbose_name='API Key'),
        ),
        migrations.AddField(
            model_name='ollamaendpoint',
            name='auth_type',
            field=models.CharField(choices=[('none', '无需认证'), ('api_key', 'API Key'), ('bearer_token', 'Bearer Token')], default='none', max_length=20, verbose_name='认证类型'),
        ),
        migrations.AddField(
            model_name='ollamaendpoint',
            name='provider',
            field=models.CharField(choices=[('ollama', 'Ollama - 本地部署'), ('zhipu', '智谱AI'), ('openai', 'OpenAI'), ('azure', 'Azure OpenAI'), ('anthropic', 'Anthropic Claude'), ('custom', '自定义API')], default='ollama', max_length=20, verbose_name='供应商类型'),
        ),
    ]
