# Generated by Django 5.2.7 on 2026-01-14 15:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='提供商名称')),
                ('slug', models.SlugField(unique=True, verbose_name='标识符')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('base_url', models.URLField(max_length=500, verbose_name='基础URL')),
                ('icon', models.URLField(blank=True, max_length=500, verbose_name='图标URL')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'AI服务提供商',
                'verbose_name_plural': 'AI服务提供商',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Endpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='端点名称')),
                ('slug', models.SlugField(verbose_name='标识符')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('auth_type', models.CharField(choices=[('none', '无认证'), ('api_key', 'API Key'), ('bearer_token', 'Bearer Token'), ('basic_auth', 'Basic Auth'), ('custom', '自定义')], default='api_key', max_length=20, verbose_name='认证类型')),
                ('api_key', models.CharField(blank=True, max_length=500, verbose_name='API Key')),
                ('api_key_header', models.CharField(blank=True, default='Authorization', max_length=50, verbose_name='API Key 请求头')),
                ('endpoint_url', models.CharField(blank=True, max_length=500, verbose_name='端点URL')),
                ('is_default', models.BooleanField(default=False, verbose_name='是否默认')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('rate_limit', models.IntegerField(blank=True, null=True, verbose_name='请求限制(次/分钟)')),
                ('max_tokens', models.IntegerField(blank=True, null=True, verbose_name='最大token数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='endpoints', to=settings.AUTH_USER_MODEL, verbose_name='所有者')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='endpoints', to='llm.provider', verbose_name='服务提供商')),
            ],
            options={
                'verbose_name': 'API端点',
                'verbose_name_plural': 'API端点',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='模型名称')),
                ('slug', models.SlugField(verbose_name='标识符')),
                ('display_name', models.CharField(max_length=100, verbose_name='显示名称')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('model_type', models.CharField(choices=[('chat', '对话模型'), ('completion', '补全模型'), ('embedding', '嵌入模型'), ('image', '图像生成'), ('vision', '视觉模型'), ('multimodal', '多模态模型')], default='chat', max_length=20, verbose_name='模型类型')),
                ('is_vision_capable', models.BooleanField(default=False, verbose_name='支持视觉')),
                ('is_streaming_supported', models.BooleanField(default=True, verbose_name='支持流式')),
                ('supports_function_calling', models.BooleanField(default=False, verbose_name='支持函数调用')),
                ('input_price', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='输入价格(分/1K tokens)')),
                ('output_price', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='输出价格(分/1K tokens)')),
                ('max_tokens', models.IntegerField(blank=True, null=True, verbose_name='最大tokens')),
                ('max_context_length', models.IntegerField(blank=True, null=True, verbose_name='最大上下文长度')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('is_public', models.BooleanField(default=True, verbose_name='是否公开')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='llm.provider', verbose_name='服务提供商')),
            ],
            options={
                'verbose_name': 'AI模型',
                'verbose_name_plural': 'AI模型',
                'ordering': ['provider', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ModelConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField(default=0.7, verbose_name='温度参数')),
                ('max_tokens', models.IntegerField(blank=True, null=True, verbose_name='最大tokens')),
                ('top_p', models.FloatField(blank=True, null=True, verbose_name='Top P')),
                ('top_k', models.IntegerField(blank=True, null=True, verbose_name='Top K')),
                ('frequency_penalty', models.FloatField(blank=True, null=True, verbose_name='频率惩罚')),
                ('presence_penalty', models.FloatField(blank=True, null=True, verbose_name='存在惩罚')),
                ('system_prompt', models.TextField(blank=True, verbose_name='系统提示词')),
                ('is_default', models.BooleanField(default=False, verbose_name='是否默认')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_configs', to='llm.endpoint', verbose_name='API端点')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configs', to='llm.aimodel', verbose_name='AI模型')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_configs', to=settings.AUTH_USER_MODEL, verbose_name='所有者')),
            ],
            options={
                'verbose_name': '模型配置',
                'verbose_name_plural': '模型配置',
                'ordering': ['-created_at'],
                'unique_together': {('owner', 'endpoint', 'model')},
            },
        ),
        migrations.AddIndex(
            model_name='endpoint',
            index=models.Index(fields=['provider'], name='llm_endpoin_provide_f16831_idx'),
        ),
        migrations.AddIndex(
            model_name='endpoint',
            index=models.Index(fields=['owner'], name='llm_endpoin_owner_i_3350f9_idx'),
        ),
        migrations.AddIndex(
            model_name='endpoint',
            index=models.Index(fields=['is_active'], name='llm_endpoin_is_acti_61c27f_idx'),
        ),
        migrations.AddIndex(
            model_name='endpoint',
            index=models.Index(fields=['-created_at'], name='llm_endpoin_created_ba36c7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='endpoint',
            unique_together={('owner', 'slug')},
        ),
        migrations.AddIndex(
            model_name='aimodel',
            index=models.Index(fields=['provider'], name='llm_aimodel_provide_f26527_idx'),
        ),
        migrations.AddIndex(
            model_name='aimodel',
            index=models.Index(fields=['model_type'], name='llm_aimodel_model_t_211b91_idx'),
        ),
        migrations.AddIndex(
            model_name='aimodel',
            index=models.Index(fields=['is_active'], name='llm_aimodel_is_acti_e910f6_idx'),
        ),
        migrations.AddIndex(
            model_name='aimodel',
            index=models.Index(fields=['is_public'], name='llm_aimodel_is_publ_f3ecd4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='aimodel',
            unique_together={('provider', 'slug')},
        ),
    ]
