# Generated by Django 5.2.7 on 2026-01-16 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0002_auto_20260116_2156'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aimodel',
            options={'ordering': ['endpoint', 'name'], 'verbose_name': 'AI模型', 'verbose_name_plural': 'AI模型'},
        ),
        migrations.AlterField(
            model_name='endpoint',
            name='name',
            field=models.CharField(max_length=100, verbose_name='名称'),
        ),
        migrations.AddIndex(
            model_name='aimodel',
            index=models.Index(fields=['endpoint'], name='llm_aimodel_endpoin_335b57_idx'),
        ),
    ]
