# Generated by Django 5.2.7 on 2026-01-17 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0003_alter_aimodel_options_alter_endpoint_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aimodel',
            options={'ordering': ['-is_default', 'endpoint', 'name'], 'verbose_name': 'AI模型', 'verbose_name_plural': 'AI模型'},
        ),
        migrations.AddField(
            model_name='aimodel',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='是否默认'),
        ),
        migrations.AddIndex(
            model_name='aimodel',
            index=models.Index(fields=['-is_default'], name='llm_aimodel_is_defa_8e15d8_idx'),
        ),
    ]
