# Generated by Django 5.2.7 on 2026-01-17 12:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0004_alter_aimodel_options_aimodel_is_default_and_more'),
        ('media', '0005_media_file_hash_media_media_media_file_ha_1bbb39_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('processing', '分析中'), ('completed', '已完成'), ('failed', '失败')], default='pending', max_length=20, verbose_name='状态')),
                ('description', models.TextField(blank=True, verbose_name='图片描述')),
                ('categories', models.JSONField(blank=True, default=list, verbose_name='分类标签')),
                ('scenes', models.JSONField(blank=True, default=list, verbose_name='场景标签')),
                ('method', models.CharField(blank=True, max_length=50, verbose_name='分析方法')),
                ('tokens_used', models.IntegerField(blank=True, null=True, verbose_name='Token消耗')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('endpoint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analyses', to='llm.endpoint', verbose_name='API端点')),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='media.media', verbose_name='媒体文件')),
                ('model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analyses', to='llm.aimodel', verbose_name='AI模型')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '图片分析',
                'verbose_name_plural': '图片分析',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['media', '-created_at'], name='llm_imagean_media_i_e57052_idx'), models.Index(fields=['user', '-created_at'], name='llm_imagean_user_id_cac187_idx'), models.Index(fields=['status'], name='llm_imagean_status_f7c96d_idx'), models.Index(fields=['-created_at'], name='llm_imagean_created_b36e35_idx')],
            },
        ),
    ]
