# Generated by Django 5.2.7 on 2026-01-17 12:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0005_add_image_analysis_model'),
        ('media', '0005_media_file_hash_media_media_media_file_ha_1bbb39_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='imageanalysis',
            name='error_details',
            field=models.JSONField(blank=True, default=dict, verbose_name='错误详情'),
        ),
        migrations.AddField(
            model_name='imageanalysis',
            name='error_type',
            field=models.CharField(choices=[('none', '无错误'), ('network', '网络错误'), ('api', 'API错误'), ('permission', '权限错误'), ('validation', '验证错误'), ('timeout', '超时'), ('rate_limit', '频率限制'), ('unknown', '未知错误')], default='none', max_length=20, verbose_name='错误类型'),
        ),
        migrations.AddField(
            model_name='imageanalysis',
            name='last_retry_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='最后重试时间'),
        ),
        migrations.AddField(
            model_name='imageanalysis',
            name='max_retries',
            field=models.IntegerField(default=3, verbose_name='最大重试次数'),
        ),
        migrations.AddField(
            model_name='imageanalysis',
            name='retry_count',
            field=models.IntegerField(default=0, verbose_name='重试次数'),
        ),
        migrations.AlterField(
            model_name='imageanalysis',
            name='status',
            field=models.CharField(choices=[('pending', '待处理'), ('processing', '分析中'), ('completed', '已完成'), ('failed', '失败'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='状态'),
        ),
        migrations.AddIndex(
            model_name='imageanalysis',
            index=models.Index(fields=['error_type'], name='llm_imagean_error_t_1a775b_idx'),
        ),
    ]
