# Generated by Django 5.2.7 on 2026-02-17 12:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0008_remove_imageanalysis_categories_scenes'),
        ('media', '0006_remove_media_tags_delete_tag'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='endpoint',
            name='api_key',
        ),
        migrations.AddField(
            model_name='endpoint',
            name='_api_key',
            field=models.CharField(blank=True, db_column='api_key', max_length=500, verbose_name='API Key（加密存储）'),
        ),
        migrations.AddIndex(
            model_name='imageanalysis',
            index=models.Index(fields=['user', 'status'], name='llm_imagean_user_id_537b1b_idx'),
        ),
        migrations.AddIndex(
            model_name='imageanalysis',
            index=models.Index(fields=['media', 'status'], name='llm_imagean_media_i_9ce5c8_idx'),
        ),
        migrations.AddIndex(
            model_name='imageanalysis',
            index=models.Index(fields=['status', '-created_at'], name='llm_imagean_status_8ae680_idx'),
        ),
        migrations.AddIndex(
            model_name='imageanalysis',
            index=models.Index(fields=['user', 'status', '-created_at'], name='llm_imagean_user_id_f36484_idx'),
        ),
    ]
