# Generated by Django 5.2.7 on 2026-02-17 14:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0009_remove_endpoint_api_key_endpoint__api_key_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='endpoint',
            options={'ordering': ['-is_default', '-created_at'], 'verbose_name': 'API端点', 'verbose_name_plural': 'API端点'},
        ),
        migrations.AddField(
            model_name='endpoint',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='是否默认端点'),
        ),
        migrations.AddIndex(
            model_name='endpoint',
            index=models.Index(fields=['-is_default'], name='llm_endpoin_is_defa_dd5630_idx'),
        ),
    ]
