# Generated by Django 5.2.7 on 2025-11-19 03:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '等待分析'), ('processing', '分析中'), ('completed', '分析完成'), ('failed', '分析失败')], default='pending', max_length=20, verbose_name='分析状态')),
                ('model_used', models.CharField(blank=True, max_length=100, null=True, verbose_name='使用的AI模型')),
                ('title', models.TextField(blank=True, null=True, verbose_name='生成标题')),
                ('description', models.TextField(blank=True, null=True, verbose_name='生成描述')),
                ('prompt', models.TextField(blank=True, null=True, verbose_name='生成提示词')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='错误信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('analyzed_at', models.DateTimeField(blank=True, null=True, verbose_name='分析完成时间')),
                ('media', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_analysis_v2', to='media.media', verbose_name='媒体文件')),
                ('suggested_categories', models.ManyToManyField(blank=True, to='media.category', verbose_name='建议分类')),
                ('suggested_tags', models.ManyToManyField(blank=True, to='media.tag', verbose_name='建议标签')),
            ],
            options={
                'verbose_name': 'AI分析',
                'verbose_name_plural': 'AI分析',
            },
        ),
        migrations.CreateModel(
            name='OllamaEndpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='端点名称')),
                ('url', models.URLField(verbose_name='服务端点URL')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('timeout', models.IntegerField(default=300, verbose_name='超时时间（秒）')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ollama_endpoints', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
            options={
                'verbose_name': 'Ollama服务端点',
                'verbose_name_plural': 'Ollama服务端点',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='模型名称')),
                ('display_name', models.CharField(max_length=100, verbose_name='显示名称')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('is_vision_capable', models.BooleanField(default=False, verbose_name='是否支持视觉')),
                ('is_default', models.BooleanField(default=False, verbose_name='是否为默认模型')),
                ('model_size', models.CharField(blank=True, max_length=50, null=True, verbose_name='模型大小')),
                ('description', models.TextField(blank=True, null=True, verbose_name='模型描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='llms.ollamaendpoint', verbose_name='所属端点')),
            ],
            options={
                'verbose_name': 'AI模型',
                'verbose_name_plural': 'AI模型',
                'ordering': ['-is_default', 'display_name'],
                'unique_together': {('name', 'endpoint')},
            },
        ),
    ]
