# Generated by Django 5.2.7 on 2025-11-19 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ollamaendpoint',
            options={'ordering': ['-is_default', '-created_at'], 'verbose_name': 'Ollama服务端点', 'verbose_name_plural': 'Ollama服务端点'},
        ),
        migrations.AddField(
            model_name='ollamaendpoint',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='是否为默认端点'),
        ),
    ]
