# Generated by Django 5.2.7 on 2025-11-20 02:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llms', '0002_alter_ollamaendpoint_options_and_more'),
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aianalysis',
            name='applied_to_media',
            field=models.BooleanField(default=False, verbose_name='是否已应用到素材库'),
        ),
        migrations.AddField(
            model_name='aianalysis',
            name='task_id',
            field=models.CharField(blank=True, help_text='异步任务ID，用于跟踪任务状态', max_length=32, null=True, verbose_name='任务ID'),
        ),
        migrations.AlterField(
            model_name='aianalysis',
            name='media',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_analysis', to='media.media', verbose_name='媒体文件'),
        ),
    ]
