# Generated by Django 5.2.7 on 2025-11-20 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llms', '0004_create_default_endpoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='aianalysis',
            name='analysis_options',
            field=models.JSONField(blank=True, help_text='分析时使用的配置选项', null=True, verbose_name='分析选项'),
        ),
    ]
