# Generated by Django 5.2.7 on 2026-01-14 13:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='分类名称')),
                ('description', models.TextField(blank=True, verbose_name='分类描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '分类',
                'verbose_name_plural': '分类',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='标签名称')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '标签',
                'verbose_name_plural': '标签',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('image', '图片'), ('video', '视频')], max_length=10, verbose_name='媒体类型')),
                ('file', models.FileField(upload_to='media/%Y/%m/', verbose_name='文件路径')),
                ('filename', models.CharField(max_length=255, verbose_name='原始文件名')),
                ('file_size', models.BigIntegerField(verbose_name='文件大小(字节)')),
                ('mime_type', models.CharField(max_length=100, verbose_name='MIME类型')),
                ('width', models.IntegerField(blank=True, null=True, verbose_name='宽度(像素)')),
                ('height', models.IntegerField(blank=True, null=True, verbose_name='高度(像素)')),
                ('duration', models.IntegerField(blank=True, null=True, verbose_name='时长(秒)')),
                ('thumbnail', models.FileField(blank=True, null=True, upload_to='media/thumbnails/%Y/%m/', verbose_name='缩略图')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media_files', to='media.category', verbose_name='分类')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to=settings.AUTH_USER_MODEL, verbose_name='所有者')),
                ('tags', models.ManyToManyField(blank=True, related_name='media_files', to='media.tag', verbose_name='标签')),
            ],
            options={
                'verbose_name': '媒体文件',
                'verbose_name_plural': '媒体文件',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['type'], name='media_media_type_b65e83_idx'), models.Index(fields=['owner'], name='media_media_owner_i_2c19bc_idx'), models.Index(fields=['created_at'], name='media_media_created_99800a_idx'), models.Index(fields=['-created_at'], name='media_media_created_9df1bb_idx')],
            },
        ),
    ]
