# Generated by Django 5.2.7 on 2025-12-08 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='prompt',
        ),
        migrations.AlterField(
            model_name='media',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='AI描述'),
        ),
    ]
