# Generated by Django 5.2.7 on 2026-01-14 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '待分析'), ('processing', '分析中'), ('completed', '分析完成'), ('failed', '分析失败')], default='pending', max_length=20, verbose_name='分析状态')),
                ('title', models.TextField(blank=True, verbose_name='图片标题')),
                ('description', models.TextField(blank=True, verbose_name='图片描述')),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='AI分类')),
                ('emotion', models.CharField(blank=True, max_length=100, verbose_name='表情/情绪')),
                ('ai_model', models.CharField(blank=True, max_length=100, verbose_name='使用的AI模型')),
                ('ai_provider', models.CharField(blank=True, max_length=50, verbose_name='AI服务提供商')),
                ('analysis_time', models.FloatField(blank=True, null=True, verbose_name='分析耗时(秒)')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('analyzed_at', models.DateTimeField(blank=True, null=True, verbose_name='分析完成时间')),
                ('media', models.OneToOneField(limit_choices_to={'type': 'image'}, on_delete=django.db.models.deletion.CASCADE, related_name='image_analysis', to='media.media', verbose_name='媒体文件')),
            ],
            options={
                'verbose_name': '图片分析',
                'verbose_name_plural': '图片分析',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='media_image_status_e39a00_idx'), models.Index(fields=['media'], name='media_image_media_i_885d4b_idx'), models.Index(fields=['-created_at'], name='media_image_created_ab0594_idx')],
            },
        ),
        migrations.CreateModel(
            name='VideoAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '待分析'), ('processing', '分析中'), ('completed', '分析完成'), ('failed', '分析失败')], default='pending', max_length=20, verbose_name='分析状态')),
                ('title', models.TextField(blank=True, verbose_name='视频标题')),
                ('description', models.TextField(blank=True, verbose_name='视频描述')),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='AI分类')),
                ('summary', models.TextField(blank=True, verbose_name='内容摘要')),
                ('scenes', models.JSONField(blank=True, default=list, verbose_name='场景列表')),
                ('ai_model', models.CharField(blank=True, max_length=100, verbose_name='使用的AI模型')),
                ('ai_provider', models.CharField(blank=True, max_length=50, verbose_name='AI服务提供商')),
                ('analysis_time', models.FloatField(blank=True, null=True, verbose_name='分析耗时(秒)')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('analyzed_at', models.DateTimeField(blank=True, null=True, verbose_name='分析完成时间')),
                ('media', models.OneToOneField(limit_choices_to={'type': 'video'}, on_delete=django.db.models.deletion.CASCADE, related_name='video_analysis', to='media.media', verbose_name='媒体文件')),
            ],
            options={
                'verbose_name': '视频分析',
                'verbose_name_plural': '视频分析',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='media_video_status_d8f6fe_idx'), models.Index(fields=['media'], name='media_video_media_i_53ac46_idx'), models.Index(fields=['-created_at'], name='media_video_created_b99966_idx')],
            },
        ),
    ]
