# Generated by Django 5.2.7 on 2026-01-14 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_imageanalysis_videoanalysis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='duration',
        ),
        migrations.AlterField(
            model_name='media',
            name='type',
            field=models.CharField(choices=[('image', '图片')], default='image', max_length=10, verbose_name='媒体类型'),
        ),
        migrations.DeleteModel(
            name='VideoAnalysis',
        ),
    ]
