# Generated by Django 5.2.7 on 2026-01-14 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0003_remove_media_duration_alter_media_type_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImageAnalysis',
        ),
    ]
