# Generated by Django 5.2.7 on 2026-01-15 14:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0004_delete_imageanalysis'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='file_hash',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='文件哈希(SHA256)'),
        ),
        migrations.AddIndex(
            model_name='media',
            index=models.Index(fields=['file_hash'], name='media_media_file_ha_1bbb39_idx'),
        ),
        migrations.AddConstraint(
            model_name='media',
            constraint=models.UniqueConstraint(fields=('owner', 'file_hash'), name='unique_owner_file_hash', violation_error_message='该图片已存在'),
        ),
    ]
