# Generated by Django 5.2.7 on 2026-01-19 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0005_media_file_hash_media_media_media_file_ha_1bbb39_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
